import { StyleSheet } from "react-native";

export default styles = StyleSheet.create({
  row: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
    padding: 10,
  },
  flexOne: {
    flex: 1,
  },
  heading: {
    fontSize: 18,
    fontWeight: "bold",
    textAlign: "left",
    flex: 1,
    color: "white",
  },
  rowEnd: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
    gap: 10,
  },
  smallRow: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 5,
  },
  nearRow: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingVertical: 10,
  },
  input: {
    padding: 5,
    backgroundColor: "lightgray",
    borderRadius: 5,
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    height: 40,
    marginVertical: 5,
  },
  inputOne: {
    padding: 5,
    backgroundColor: "lightgray",
    borderRadius: 5,
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    height: 40,
    marginVertical: 5,
    flex: 1,
  },
  inputRow: {
    padding: 5,
    backgroundColor: "lightgray",
    borderRadius: 5,
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    alignItems: "center",
    gap: 10,
    padding: 10,
  },
  button: {
    padding: 5,
    backgroundColor: "blue",
    borderRadius: 5,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    height: 40,
    marginVertical: 5,
  },
  buttonOne: {
    padding: 5,
    backgroundColor: "blue",
    borderRadius: 5,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    height: 40,
    marginVertical: 5,
    flex: 1,
  },
  buttonSecOne: {
    padding: 5,
    backgroundColor: "lightgray",
    borderRadius: 5,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    height: 40,
    marginVertical: 5,
    flex: 1,
  },
  rowNoPad: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
  },
});
